site_name: Unitystation
site_url: 'https://unitystation.github.io/unitystation-wiki/'
nav:
    - github: 'https://github.com/Unitystation-fork/Unitystation-WikiV2'
    - Home: index.md
    - About: about.md



theme: windmill
    #- name: null
    #- custom_dir: theme/
    #- static_templates:
     #   - 404.html
    #- include_search_page: true
    #- search_index_only: true
    #- history_buttons: true
    #- article_nav_top: true
    #- article_nav_bottom: true
    #- language: en

extra:                                              # Language Selection
  alternate:  

      # Switch to English
    - name: English
      link: /en/
      lang: en

    # Switch to Dutch
    - name: Russia
      link: /ru/
      lang: ru

    # Switch to French
    - name: Fran√ßais
      link: /fr/
      lang: fr



